//! `b10x-domain-graph/1` documents from the compiled ESS model (`ess specify compile --format json`).
use serde_json::{json, Map, Value};

/// Recorded in each document's `domain.source`, since JSON carries no comment.
pub const SOURCE: &str = "generated by cortex-docs from spec/ (ess specify compile); do not edit";

fn text<'a>(value: &'a Value, key: &str) -> Result<&'a str, String> {
    value[key]
        .as_str()
        .ok_or_else(|| format!("compiled model: `{key}` is not a string in {value}"))
}

fn strings(value: &Value) -> Vec<Value> {
    value
        .as_array()
        .map(|items| {
            items
                .iter()
                .filter(|item| item.is_string())
                .cloned()
                .collect()
        })
        .unwrap_or_default()
}

/// The last segment of a fully qualified name.
fn short(name: &str) -> &str {
    name.rsplit('.').next().unwrap_or(name)
}

/// A type reference as the graph shows it: `SourceId`, `integer`, `Optional<decimal>`.
pub fn type_name(reference: &Value) -> Result<String, String> {
    let kind = text(reference, "kind")?;
    match kind {
        "primitive" => Ok(text(reference, "name")?.to_owned()),
        "declared" => Ok(short(text(reference, "name")?).to_owned()),
        _ => {
            let Some(of) = reference.get("of") else {
                return Err(format!(
                    "compiled model: unsupported type reference {reference}"
                ));
            };
            let mut wrapper = kind.to_owned();
            wrapper[..1].make_ascii_uppercase();
            Ok(format!("{wrapper}<{}>", type_name(of)?))
        }
    }
}

fn field(value: &Value) -> Result<Value, String> {
    Ok(json!({"name": text(value, "name")?, "type": type_name(&value["type_ref"])?}))
}

fn lifecycle(value: &Value) -> Result<Value, String> {
    let mut out = Map::new();
    out.insert("initial".into(), json!(text(value, "initial")?));
    out.insert("states".into(), Value::Array(strings(&value["states"])));
    let terminal = strings(&value["terminal"]);
    if !terminal.is_empty() {
        out.insert("terminal".into(), Value::Array(terminal));
    }
    if let Some(transitions) = value["transitions"].as_array() {
        let transitions = transitions
            .iter()
            .map(|transition| {
                Ok(json!({
                    "name": text(transition, "name")?,
                    "from": strings(&transition["from"]),
                    "to": text(transition, "to")?,
                }))
            })
            .collect::<Result<Vec<_>, String>>()?;
        if !transitions.is_empty() {
            out.insert("transitions".into(), Value::Array(transitions));
        }
    }
    Ok(Value::Object(out))
}

/// One domain of the compiled model as a `b10x-domain-graph/1` document.
pub fn domain_graph(model: &Value, domain: &str) -> Result<Value, String> {
    let declared = &model["domains"][domain];
    let naming = &declared["naming"];
    let mut header = Map::new();
    header.insert("id".into(), json!(domain));
    for (key, source) in [("display", "display"), ("summary", "summary")] {
        if let Some(value) = naming[source].as_str() {
            header.insert(key.into(), json!(value));
        }
    }
    header.insert("system".into(), json!(text(model, "system")?));
    header.insert("source".into(), json!(SOURCE));

    let mut names: Vec<&str> = declared["entities"]
        .as_array()
        .ok_or_else(|| format!("compiled model: domain {domain} lists no entities"))?
        .iter()
        .filter_map(Value::as_str)
        .collect();
    names.sort_unstable();

    let mut entities = Vec::new();
    let mut relations = Vec::new();
    for name in names {
        let entity = &model["entities"][name];
        let mut out = Map::new();
        out.insert("id".into(), json!(name));
        out.insert("name".into(), json!(short(name)));
        out.insert("identity".into(), field(&entity["identity"])?);
        let fields = entity["fields"]
            .as_array()
            .map(|fields| fields.iter().map(field).collect::<Result<Vec<_>, String>>())
            .transpose()?
            .unwrap_or_default();
        out.insert("fields".into(), Value::Array(fields));
        if entity["lifecycle"].is_object() {
            out.insert("lifecycle".into(), lifecycle(&entity["lifecycle"])?);
        }
        entities.push(Value::Object(out));
        for relation in entity["relations"].as_array().into_iter().flatten() {
            let mut edge = Map::new();
            edge.insert("from".into(), json!(name));
            edge.insert("to".into(), json!(text(relation, "target")?));
            edge.insert("name".into(), json!(text(relation, "name")?));
            edge.insert("kind".into(), json!(text(relation, "kind")?));
            edge.insert("cardinality".into(), json!(text(relation, "cardinality")?));
            if let Some(via) = relation["via"].as_str() {
                edge.insert("via".into(), json!(via));
            }
            relations.push(Value::Object(edge));
        }
    }
    Ok(json!({
        "format": "b10x-domain-graph/1",
        "domain": Value::Object(header),
        "entities": entities,
        "relations": relations,
    }))
}

/// Every domain of the compiled model, keyed by domain id.
pub fn domain_graphs(model: &Value) -> Result<Vec<(String, Value)>, String> {
    let domains = model["domains"]
        .as_object()
        .ok_or("compiled model has no domains")?;
    domains
        .keys()
        .map(|domain| Ok((domain.clone(), domain_graph(model, domain)?)))
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;

    fn model() -> Value {
        json!({
            "system": "cortex",
            "domains": {"cortex.instance": {
                "naming": {"display": "Instances", "summary": "Instances and sources."},
                "entities": ["cortex.instance.Source", "cortex.instance.Instance"]
            }},
            "entities": {
                "cortex.instance.Instance": {
                    "identity": {"name": "name", "type_ref": {"kind": "declared", "name": "cortex.instance.InstanceName"}},
                    "fields": [{"name": "model", "type_ref": {"kind": "optional", "of": {"kind": "primitive", "name": "string"}}}],
                    "lifecycle": {"initial": "Active", "states": ["Active", "Removed"], "terminal": ["Removed"],
                        "transitions": [{"name": "remove", "from": ["Active"], "to": "Removed"}]},
                    "relations": [{"name": "sources", "kind": "owns", "target": "cortex.instance.Source", "cardinality": "many", "via": "instance_name"}]
                },
                "cortex.instance.Source": {
                    "identity": {"name": "source_id", "type_ref": {"kind": "declared", "name": "cortex.instance.SourceId"}},
                    "fields": [{"name": "runs", "type_ref": {"kind": "primitive", "name": "integer"}}],
                    "lifecycle": {"initial": "Enabled", "states": ["Enabled", "Disabled"], "terminal": []},
                    "relations": []
                }
            }
        })
    }

    #[test]
    fn a_domain_becomes_a_sorted_graph_with_short_type_names() {
        let graphs = domain_graphs(&model()).unwrap();
        assert_eq!(graphs.len(), 1);
        let (id, graph) = &graphs[0];
        assert_eq!(id, "cortex.instance");
        assert_eq!(graph["format"], "b10x-domain-graph/1");
        assert_eq!(graph["domain"]["display"], "Instances");
        assert_eq!(graph["domain"]["source"], SOURCE);
        let names: Vec<_> = graph["entities"]
            .as_array()
            .unwrap()
            .iter()
            .map(|entity| entity["id"].as_str().unwrap())
            .collect();
        assert_eq!(
            names,
            ["cortex.instance.Instance", "cortex.instance.Source"]
        );
        let instance = &graph["entities"][0];
        assert_eq!(
            instance["identity"],
            json!({"name": "name", "type": "InstanceName"})
        );
        assert_eq!(instance["fields"][0]["type"], "Optional<string>");
        assert_eq!(instance["lifecycle"]["transitions"][0]["to"], "Removed");
        assert!(graph["entities"][1]["lifecycle"].get("terminal").is_none());
        assert_eq!(
            graph["relations"][0],
            json!({"from": "cortex.instance.Instance", "to": "cortex.instance.Source",
                   "name": "sources", "kind": "owns", "cardinality": "many", "via": "instance_name"})
        );
    }

    #[test]
    fn an_unknown_type_reference_is_refused() {
        assert!(type_name(&json!({"kind": "mystery"})).is_err());
        assert_eq!(
            type_name(&json!({"kind": "list", "of": {"kind": "declared", "name": "a.b.C"}}))
                .unwrap(),
            "List<C>"
        );
    }
}
