#![forbid(unsafe_code)]
//! Generates the derivable part of the documentation site under `website/`, checks it for drift,
//! and binds a built site to its source commit. The site build itself is Docusaurus.
//!
//! Everything generated comes from `spec/` through `ess`: the domain reference pages from
//! `ess generate --kind docs`, one `b10x-domain-graph/1` document per domain from
//! `ess specify compile`, and the spec file's JSON Schema from `ess generate --kind schema`.
mod graph;

use std::{
    collections::BTreeMap,
    ffi::OsStr,
    fs,
    path::{Path, PathBuf},
    process::{Command, ExitCode},
};

use clap::{Parser, Subcommand};

type Result<T> = std::result::Result<T, String>;

/// The line every generated Markdown page carries directly after its front matter.
const HEADER: &str = "<!-- generated by cortex-docs, do not edit -->";
/// The same line in an MDX page, where HTML comments are not allowed.
const MDX_HEADER: &str = "{/* generated by cortex-docs, do not edit */}";
/// Where the ESS reference pages land, relative to the repository root.
const ESS_REFERENCE: &str = "website/docs/reference/ess";
/// Where the domain graphs land, relative to the repository root.
const ESS_DATA: &str = "website/data/ess";
/// Where the spec file's JSON Schema lands, relative to the repository root.
const SCHEMAS: &str = "website/static/schemas";
/// The spec file's JSON Schema as published, under `SCHEMAS`.
const SPEC_SCHEMA: &str = "instance-spec.schema.json";
/// The spec file's root type, as `ess generate --kind schema` names its file.
const SPEC_TYPE: &str = "schema/types/cortex.instance.InstanceSpec.schema.json";
/// Every documentation page, generated or written by hand, relative to the repository root.
const DOCS: &str = "website/docs";
/// The route the site is served under.
const BASE_URL: &str = "/cortex/";

#[derive(Parser)]
#[command(about = "Generate and check the derived pages of the cortex documentation site")]
struct Cli {
    #[command(subcommand)]
    command: Action,
}

#[derive(Subcommand)]
enum Action {
    /// Regenerate the derived files under website/ from spec/, or check them for drift.
    Generate {
        /// Write nothing; fail when a generated file is missing, stale or hand-edited.
        #[arg(long)]
        check: bool,
        /// Repository root.
        #[arg(long, default_value = ".")]
        root: PathBuf,
        /// The `ess` executable.
        #[arg(long, default_value = "ess")]
        ess: PathBuf,
    },
    /// Bind a built site to its source commit: write `.well-known/b10x-site.json` into it.
    Provenance {
        /// The built site, `website/build`.
        #[arg(long)]
        site: PathBuf,
        /// The full Git revision the site was built from.
        #[arg(long)]
        commit: String,
    },
}

/// Whether `line` matches `^:::[a-z]+ +\S`: an admonition whose title is not in brackets, which
/// Docusaurus prints as raw text.
fn is_raw_admonition(line: &str) -> bool {
    let Some(rest) = line.strip_prefix(":::") else {
        return false;
    };
    let kind = rest.bytes().take_while(u8::is_ascii_lowercase).count();
    let rest = &rest[kind..];
    let spaces = rest.bytes().take_while(|b| *b == b' ').count();
    kind > 0
        && spaces > 0
        && rest[spaces..]
            .chars()
            .next()
            .is_some_and(|c| !c.is_whitespace())
}

fn io(context: impl std::fmt::Display) -> impl FnOnce(std::io::Error) -> String {
    move |e| format!("{context}: {e}")
}

/// Directory entries of `dir`, sorted by path.
fn sorted_entries(dir: &Path) -> Result<Vec<fs::DirEntry>> {
    let mut entries = fs::read_dir(dir)
        .map_err(io(dir.display()))?
        .collect::<std::io::Result<Vec<_>>>()
        .map_err(io(dir.display()))?;
    entries.sort_by_key(|entry| entry.path());
    Ok(entries)
}

/// `file:line` of every raw admonition title in the Markdown and MDX pages under `dir`.
fn raw_admonitions(dir: &Path) -> Result<Vec<String>> {
    let mut found = Vec::new();
    for entry in sorted_entries(dir)? {
        let path = entry.path();
        if path.is_dir() {
            found.extend(raw_admonitions(&path)?);
        } else if path
            .extension()
            .is_some_and(|ext| ext == "md" || ext == "mdx")
        {
            let text = fs::read_to_string(&path).map_err(io(path.display()))?;
            for (n, line) in text.lines().enumerate() {
                if is_raw_admonition(line) {
                    found.push(format!("{}:{}", path.display(), n + 1));
                }
            }
        }
    }
    Ok(found)
}

/// The project-site publication record for one build of the `/cortex/` site.
fn site_manifest(commit: &str) -> Result<String> {
    if commit.len() != 40
        || !commit.bytes().all(|b| b.is_ascii_hexdigit())
        || commit == "0".repeat(40)
    {
        return Err("commit must be a nonzero full Git revision".into());
    }
    Ok(format!(
        "{{\n  \"baseUrl\": \"{BASE_URL}\",\n  \"commit\": \"{commit}\",\n  \"repository\": \"cortex\",\n  \"schema\": \"b10x-project-site/v1\"\n}}"
    ))
}

fn write_provenance(site: &Path, commit: &str) -> Result<()> {
    let manifest = site_manifest(commit)?;
    if !site.join("index.html").is_file() {
        return Err(format!("{} holds no built site", site.display()));
    }
    let well_known = site.join(".well-known");
    fs::create_dir_all(&well_known).map_err(io(well_known.display()))?;
    fs::write(well_known.join("b10x-site.json"), manifest).map_err(io("site provenance"))?;
    fs::write(site.join(".nojekyll"), "").map_err(io(".nojekyll"))?;
    Ok(())
}

/// Files keyed by file name, in the order they are written.
type Pages = BTreeMap<String, String>;

/// Strip the leading HTML comment `ess generate` writes, returning the rest.
fn strip_ess_banner(page: &str) -> Result<&str> {
    let rest = page
        .strip_prefix("<!--")
        .ok_or("ess page does not open with its provenance comment")?;
    let end = rest
        .find("-->")
        .ok_or("ess provenance comment is not closed")?;
    Ok(rest[end + 3..].trim_start_matches('\n'))
}

/// The H1 title and the first paragraph after it.
fn title_and_summary(body: &str) -> Result<(String, String)> {
    let mut lines = body.lines();
    let title = lines
        .next()
        .and_then(|line| line.strip_prefix("# "))
        .ok_or("ess page does not open with a level-one heading")?
        .trim()
        .to_owned();
    let summary = lines
        .skip_while(|line| line.trim().is_empty())
        .take_while(|line| !line.trim().is_empty())
        .collect::<Vec<_>>()
        .join(" ");
    if summary.is_empty() {
        return Err(format!("ess page {title} has no summary"));
    }
    Ok((title, summary))
}

fn yaml_string(value: &str) -> String {
    format!("\"{}\"", value.replace('\\', "\\\\").replace('"', "\\\""))
}

fn front_matter(title: &str, label: &str, description: &str, header: &str) -> String {
    format!(
        "---\ntitle: {}\nsidebar_label: {}\ndescription: {}\n---\n\n{header}\n\n",
        yaml_string(title),
        yaml_string(label),
        yaml_string(description),
    )
}

/// One domain page of `ess generate --kind docs`, rewritten as a site page. The level-one heading
/// is dropped so the front matter's title heads the page: the domain's display name can equal a
/// view's name (`Instances`), and two equal headings would move the view's anchor.
fn domain_page(source: &str) -> Result<(String, String, String)> {
    let body = strip_ess_banner(source)?;
    let (title, summary) = title_and_summary(body)?;
    let body = body
        .split_once('\n')
        .map_or("", |(_, rest)| rest)
        .trim_start_matches('\n')
        .replace(
            "[Back to the index](../index.md)",
            "[All domains](./index.mdx)",
        )
        .replace("`ess generate`", "`task generate`");
    if body.contains("](../") {
        return Err(format!(
            "ess page {title} links outside the generated domain pages"
        ));
    }
    let page = front_matter(
        &format!("{title} domain"),
        &title,
        &format!("ESS reference for the {title} domain, generated from the specification."),
        HEADER,
    ) + &body;
    Ok((title, summary, page))
}

/// One domain as the index lists it.
struct DomainEntry {
    page: String,
    graph: String,
    title: String,
    summary: String,
}

/// The reference index: one `<DomainGraph>` per domain, then a link to its full page.
fn index_page(domains: &[DomainEntry]) -> String {
    let mut page = front_matter(
        "ESS specification",
        "ESS specification",
        "The cortex specification, domain by domain, generated from spec/ in the repository.",
        MDX_HEADER,
    );
    for (n, domain) in domains.iter().enumerate() {
        page.push_str(&format!(
            "import domainGraph{n} from '@site/data/ess/{}';\n",
            domain.graph
        ));
    }
    page.push_str("\n# ESS specification\n\n");
    page.push_str(
        "cortex is specified in ESS. This page and the domain pages below are generated from the \
         repository's `spec/` directory by `cortex-docs`: the graphs from `ess specify compile`, \
         the pages from `ess generate --kind docs`. They change when the specification changes, \
         and `task check` fails if they fall behind it.\n\n\
         The spec file an instance is created from is the type `InstanceSpec` below. Its JSON \
         Schema, generated by `ess generate --kind schema`, is published at \
         [`instance-spec.schema.json`](https://beyond10x.github.io/cortex/schemas/instance-spec.schema.json); \
         `cortex schema` prints the same document.\n",
    );
    for (n, domain) in domains.iter().enumerate() {
        page.push_str(&format!(
            "\n## {title}\n\n{summary}\n\n<DomainGraph data={{domainGraph{n}}} title=\"{title}\" />\n\n\
             [Read the {title} domain in full](./{file})\n",
            title = domain.title,
            summary = domain.summary,
            file = domain.page,
        ));
    }
    page
}

/// Generated files: directory relative to the repository root, then file name, then content.
type Outputs = BTreeMap<&'static str, Pages>;

fn run(ess: &Path, args: &[&OsStr]) -> Result<Vec<u8>> {
    let output = Command::new(ess)
        .args(args)
        .output()
        .map_err(io(format!("running {}", ess.display())))?;
    if !output.status.success() {
        return Err(format!(
            "{} {} failed: {}",
            ess.display(),
            args.iter()
                .map(|arg| arg.to_string_lossy())
                .collect::<Vec<_>>()
                .join(" "),
            String::from_utf8_lossy(&output.stderr)
        ));
    }
    Ok(output.stdout)
}

/// `ess generate --kind <kind>` over `spec` into `out`.
fn ess_generate(ess: &Path, spec: &Path, kind: &str, out: &Path) -> Result<()> {
    run(
        ess,
        &[
            "generate".as_ref(),
            "--path".as_ref(),
            spec.as_os_str(),
            "--kind".as_ref(),
            kind.as_ref(),
            "--out".as_ref(),
            out.as_os_str(),
            "--strict-requires".as_ref(),
        ],
    )
    .map(drop)
}

/// The domain pages and the index, from `ess generate --kind docs` in `scratch`.
fn reference_pages(ess: &Path, spec: &Path, scratch: &Path, graphs: &Pages) -> Result<Pages> {
    let out = scratch.join("docs");
    ess_generate(ess, spec, "docs", &out)?;
    let mut pages = Pages::new();
    let mut index = Vec::new();
    for entry in sorted_entries(&out.join("docs/domains"))? {
        let name = entry.file_name().to_string_lossy().into_owned();
        let Some(stem) = name.strip_suffix(".md") else {
            continue;
        };
        let graph = format!("{stem}.domain-graph.json");
        if !graphs.contains_key(&graph) {
            return Err(format!(
                "ess page {name} has no domain in the compiled model"
            ));
        }
        let source = fs::read_to_string(entry.path()).map_err(io(entry.path().display()))?;
        let (title, summary, page) = domain_page(&source)?;
        index.push(DomainEntry {
            page: name.clone(),
            graph,
            title,
            summary,
        });
        pages.insert(name, page);
    }
    if index.is_empty() {
        return Err("ess generated no domain pages".into());
    }
    if index.len() != graphs.len() {
        return Err(format!(
            "ess generated {} domain pages for {} domains",
            index.len(),
            graphs.len()
        ));
    }
    pages.insert("index.mdx".to_owned(), index_page(&index));
    Ok(pages)
}

/// The spec file's JSON Schema, from `ess generate --kind schema` in `scratch`.
fn spec_schema(ess: &Path, spec: &Path, scratch: &Path) -> Result<Pages> {
    let out = scratch.join("schema");
    ess_generate(ess, spec, "schema", &out)?;
    let path = out.join(SPEC_TYPE);
    let schema = fs::read_to_string(&path).map_err(io(path.display()))?;
    Ok(Pages::from([(SPEC_SCHEMA.to_owned(), schema)]))
}

/// Run `ess` and build every generated file of the site.
fn ess_outputs(root: &Path, ess: &Path) -> Result<Outputs> {
    let spec = root.join("spec");
    let compiled = run(
        ess,
        &[
            "specify".as_ref(),
            "compile".as_ref(),
            "--path".as_ref(),
            spec.as_os_str(),
            "--format".as_ref(),
            "json".as_ref(),
        ],
    )?;
    let model: serde_json::Value = serde_json::from_slice(&compiled)
        .map_err(|e| format!("parsing the compiled ESS model: {e}"))?;
    let mut graphs = Pages::new();
    for (domain, graph) in graph::domain_graphs(&model)? {
        let name = format!("{}.domain-graph.json", domain.replace('.', "-"));
        let text = serde_json::to_string_pretty(&graph).map_err(|e| e.to_string())?;
        graphs.insert(name, text + "\n");
    }

    let scratch = std::env::temp_dir().join(format!("cortex-docs-{}", std::process::id()));
    if scratch.exists() {
        fs::remove_dir_all(&scratch).map_err(io(scratch.display()))?;
    }
    let pages = reference_pages(ess, &spec, &scratch, &graphs);
    let schemas = pages
        .is_ok()
        .then(|| spec_schema(ess, &spec, &scratch))
        .transpose();
    let _ = fs::remove_dir_all(&scratch);
    let pages = pages?;
    let schemas = schemas?.expect("generated after the pages");
    Ok(Outputs::from([
        (ESS_REFERENCE, pages),
        (ESS_DATA, graphs),
        (SCHEMAS, schemas),
    ]))
}

/// Every difference between the expected files and the files in `dir`.
fn drift(expected: &Pages, dir: &Path) -> Result<Vec<String>> {
    let mut actual = Pages::new();
    if dir.exists() {
        for entry in sorted_entries(dir)? {
            let name = entry.file_name().to_string_lossy().into_owned();
            let text = fs::read_to_string(entry.path()).map_err(io(entry.path().display()))?;
            actual.insert(name, text);
        }
    }
    let mut problems = Vec::new();
    for (name, content) in expected {
        match actual.get(name) {
            None => problems.push(format!("missing {name}")),
            Some(found) if found != content => problems.push(format!("stale or edited {name}")),
            Some(_) => {}
        }
    }
    for name in actual.keys().filter(|name| !expected.contains_key(*name)) {
        problems.push(format!("not generated {name}"));
    }
    Ok(problems)
}

fn generate(root: &Path, ess: &Path, check: bool) -> Result<()> {
    let outputs = ess_outputs(root, ess)?;
    for (relative, files) in &outputs {
        let dir = root.join(relative);
        if check {
            let problems = drift(files, &dir)?;
            if !problems.is_empty() {
                return Err(format!(
                    "{relative} has drifted ({}); run `task docs-generate`",
                    problems.join(", ")
                ));
            }
            println!("{relative}: {} generated files current", files.len());
        } else {
            if dir.exists() {
                fs::remove_dir_all(&dir).map_err(io(dir.display()))?;
            }
            fs::create_dir_all(&dir).map_err(io(dir.display()))?;
            for (name, content) in files {
                fs::write(dir.join(name), content).map_err(io(dir.join(name).display()))?;
            }
            println!("{relative}: wrote {} files", files.len());
        }
    }
    let raw = raw_admonitions(&root.join(DOCS))?;
    if !raw.is_empty() {
        return Err(format!(
            "raw admonition titles (write `:::kind[Title]`): {}",
            raw.join(", ")
        ));
    }
    println!("{DOCS}: no raw admonition titles");
    Ok(())
}

fn main() -> ExitCode {
    let result = match Cli::parse().command {
        Action::Generate { check, root, ess } => generate(&root, &ess, check),
        Action::Provenance { site, commit } => write_provenance(&site, &commit)
            .map(|()| println!("{}: bound to {commit}", site.display())),
    };
    match result {
        Ok(()) => ExitCode::SUCCESS,
        Err(e) => {
            eprintln!("cortex-docs: {e}");
            ExitCode::FAILURE
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    const SAMPLE: &str = "<!--\ngenerated from cortex v1\ndo not edit: regenerate with `ess generate`\n-->\n\n# Instances\n\nInstances of a knowledge brain.\nAnd their sources.\n\n`cortex.instance` is one of cortex's bounded contexts. [Back to the index](../index.md).\n\nDo not edit this file; regenerate it with `ess generate`.\n";

    fn scratch(name: &str) -> PathBuf {
        let dir =
            std::env::temp_dir().join(format!("cortex-docs-test-{name}-{}", std::process::id()));
        let _ = fs::remove_dir_all(&dir);
        fs::create_dir_all(&dir).unwrap();
        dir
    }

    #[test]
    fn domain_pages_carry_the_header_and_no_ess_banner() {
        let (title, summary, page) = domain_page(SAMPLE).unwrap();
        assert_eq!(title, "Instances");
        assert_eq!(
            summary,
            "Instances of a knowledge brain. And their sources."
        );
        assert!(page.starts_with("---\ntitle: \"Instances domain\"\n"));
        assert!(page.contains(HEADER));
        assert!(!page.contains("<!--\ngenerated from"));
        assert!(!page.contains("# Instances\n"));
        assert!(page.contains(&format!("{HEADER}\n\nInstances of a knowledge brain.")));
        assert!(page.contains("[All domains](./index.mdx)"));
        assert!(page.contains("`task generate`"));
        assert!(!page.contains("`ess generate`"));
    }

    #[test]
    fn links_out_of_the_domain_set_are_refused() {
        let page = SAMPLE.replace("bounded contexts.", "bounded contexts. [x](../topology.md)");
        assert!(domain_page(&page).is_err());
    }

    #[test]
    fn index_renders_one_graph_per_domain_under_the_header() {
        let page = index_page(&[DomainEntry {
            page: "cortex-instance.md".into(),
            graph: "cortex-instance.domain-graph.json".into(),
            title: "Instances".into(),
            summary: "Instances and sources.".into(),
        }]);
        assert!(page.contains(MDX_HEADER));
        assert!(page.contains(
            "import domainGraph0 from '@site/data/ess/cortex-instance.domain-graph.json';"
        ));
        assert!(page.contains("<DomainGraph data={domainGraph0} title=\"Instances\" />"));
        assert!(page.contains("[Read the Instances domain in full](./cortex-instance.md)"));
        assert!(page.contains("schemas/instance-spec.schema.json"));
    }

    #[test]
    fn provenance_names_the_commit_and_refuses_a_bad_one() {
        assert!(site_manifest("abc").is_err());
        assert!(site_manifest(&"0".repeat(40)).is_err());
        assert!(site_manifest(&"g".repeat(40)).is_err());
        let commit = "0123456789abcdef0123456789abcdef01234567";
        let site = scratch("provenance");
        assert!(write_provenance(&site, commit).is_err());
        fs::write(site.join("index.html"), "<html></html>").unwrap();
        write_provenance(&site, commit).unwrap();
        let written = fs::read_to_string(site.join(".well-known/b10x-site.json")).unwrap();
        let manifest: serde_json::Value = serde_json::from_str(&written).unwrap();
        assert_eq!(manifest["schema"], "b10x-project-site/v1");
        assert_eq!(manifest["repository"], "cortex");
        assert_eq!(manifest["commit"], commit);
        assert_eq!(manifest["baseUrl"], "/cortex/");
        assert!(site.join(".nojekyll").is_file());
        let _ = fs::remove_dir_all(&site);
    }

    #[test]
    fn raw_admonition_titles_are_found_and_bracketed_ones_pass() {
        assert!(is_raw_admonition(":::note Planned"));
        assert!(!is_raw_admonition(":::note[Planned]"));
        assert!(!is_raw_admonition(":::note"));
        assert!(!is_raw_admonition(":::"));
        let dir = scratch("admonitions");
        fs::create_dir_all(dir.join("nested")).unwrap();
        fs::write(dir.join("a.md"), "# A\n\n:::tip[Fine]\nx\n:::\n").unwrap();
        fs::write(dir.join("nested/b.mdx"), "# B\n\n:::caution Raw\nx\n:::\n").unwrap();
        let found = raw_admonitions(&dir).unwrap();
        assert_eq!(found.len(), 1);
        assert!(found[0].ends_with("nested/b.mdx:3"));
        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn drift_names_missing_edited_and_stray_pages() {
        let dir = scratch("drift");
        fs::write(dir.join("edited.md"), "hand edit").unwrap();
        fs::write(dir.join("stray.md"), "x").unwrap();
        fs::write(dir.join("same.md"), "same").unwrap();
        let expected = Pages::from([
            ("edited.md".to_owned(), "generated".to_owned()),
            ("missing.md".to_owned(), "generated".to_owned()),
            ("same.md".to_owned(), "same".to_owned()),
        ]);
        let mut problems = drift(&expected, &dir).unwrap();
        problems.sort();
        assert_eq!(
            problems,
            [
                "missing missing.md",
                "not generated stray.md",
                "stale or edited edited.md"
            ]
        );
        let _ = fs::remove_dir_all(&dir);
    }
}
