import type {Config} from '@docusaurus/types';
import type * as Preset from '@docusaurus/preset-classic';
import {withProductSite} from '@beyond10x/docs-system/product-site';

// Pages under docs/reference/, files under data/ess/ and static/schemas/ are generated by
// `cortex-docs generate`; everything else is written by hand.
const config: Config = {
  title: 'cortex',
  tagline: 'Spin up EKR knowledge instances from one spec file, fed on a schedule.',
  favicon: 'img/mark.svg',

  future: {
    v4: true,
  },

  url: 'https://beyond10x.github.io',
  baseUrl: '/cortex/',

  organizationName: 'beyond10x',
  projectName: 'cortex',
  deploymentBranch: 'gh-pages',
  trailingSlash: false,

  onBrokenLinks: 'throw',
  onBrokenAnchors: 'throw',

  markdown: {
    format: 'detect',
    hooks: {
      onBrokenMarkdownLinks: 'throw',
    },
    mermaid: true,
  },

  themes: ['@docusaurus/theme-mermaid'],

  i18n: {
    defaultLocale: 'en',
    locales: ['en'],
  },

  presets: [
    [
      'classic',
      {
        docs: {
          sidebarPath: './sidebars.ts',
          routeBasePath: 'docs',
          editUrl: 'https://github.com/beyond10x/cortex/tree/main/website/',
        },
        blog: false,
      } satisfies Preset.Options,
    ],
  ],

  themeConfig: {
    navbar: {
      title: 'cortex',
      items: [
        {to: '/docs/', label: 'Documentation', position: 'left'},
        {to: '/docs/spec-file', label: 'Spec file', position: 'left'},
        {to: '/docs/commands', label: 'Commands', position: 'left'},
        {to: '/docs/reference/ess', label: 'Specification', position: 'left'},
        {href: 'https://github.com/beyond10x/cortex', label: 'GitHub', position: 'right'},
      ],
    },
    footer: {
      links: [
        {
          title: 'Documentation',
          items: [
            {label: 'Overview', to: '/docs/'},
            {label: 'Quickstart', to: '/docs/quickstart'},
            {label: 'Spec file', to: '/docs/spec-file'},
            {label: 'Commands', to: '/docs/commands'},
            {label: 'Operating an instance', to: '/docs/operating'},
            {label: 'Limits', to: '/docs/limits'},
            {label: 'ESS specification', to: '/docs/reference/ess'},
          ],
        },
        {
          title: 'Project',
          items: [{label: 'Source', href: 'https://github.com/beyond10x/cortex'}],
        },
      ],
      copyright: 'A beyond10x project. cortex · Apache-2.0.',
    },
  } satisfies Preset.ThemeConfig,
};

export default withProductSite(config, {landing: './product.json'});
