import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    {
      type: 'category',
      label: 'Start here',
      collapsed: false,
      items: ['index', 'quickstart', 'use-cases', 'status'],
    },
    {
      type: 'category',
      label: 'Using cortex',
      collapsed: false,
      items: ['spec-file', 'commands', 'operating', 'limits'],
    },
    {
      type: 'category',
      label: 'Reference',
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'reference'}],
    },
  ],
};

export default sidebars;
